import 'package:dio/dio.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/api/api_config.dart';
import '../../../core/api/dio_client.dart';
import '../../../core/errors/error_mapper.dart';
import '../../../core/errors/failure.dart';
import '../../../shared/models/order_models.dart';

/// `/api/orders`.
class OrdersRepository {
  OrdersRepository(this._dio);

  final Dio _dio;

  /// Submits the active cart.
  ///
  /// [idempotencyKey] is generated by the caller, **once per submit attempt**,
  /// and must be reused verbatim on every retry of that attempt. The server
  /// replays the original `201` for a repeated key, which is the only thing
  /// standing between a flaky warehouse Wi-Fi connection and duplicate orders.
  Future<OrderDetail> submitOrder({
    required String storeId,
    required String idempotencyKey,
    String? notes,
  }) async {
    try {
      final response = await _dio.post<Map<String, dynamic>>(
        ApiPaths.orders,
        options: Options(
          headers: <String, dynamic>{ApiHeaders.idempotencyKey: idempotencyKey},
        ),
        data: <String, dynamic>{
          'storeId': storeId,
          if (notes != null && notes.isNotEmpty) 'notes': notes,
        },
      );
      return OrderEnvelope.fromJson(_require(response.data)).order;
    } on Object catch (error, stackTrace) {
      throw mapError(error, stackTrace);
    }
  }

  Future<OrderPage> fetchOrders({
    required String storeId,
    String? status,
    int limit = 20,
    int offset = 0,
  }) async {
    try {
      final response = await _dio.get<Map<String, dynamic>>(
        ApiPaths.orders,
        queryParameters: <String, dynamic>{
          'storeId': storeId,
          if (status != null && status.isNotEmpty) 'status': status,
          'limit': limit,
          'offset': offset,
        },
      );
      return OrderPage.fromJson(_require(response.data));
    } on Object catch (error, stackTrace) {
      throw mapError(error, stackTrace);
    }
  }

  Future<OrderDetail> fetchOrder(String orderId) async {
    try {
      final response = await _dio.get<Map<String, dynamic>>(
        ApiPaths.order(orderId),
      );
      return OrderDetail.fromJson(_require(response.data));
    } on Object catch (error, stackTrace) {
      throw mapError(error, stackTrace);
    }
  }

  static Map<String, dynamic> _require(Map<String, dynamic>? data) {
    if (data == null) {
      throw const Failure.unexpected(message: 'The server returned no data.');
    }
    return data;
  }
}

final ordersRepositoryProvider = Provider<OrdersRepository>(
  (ref) => OrdersRepository(ref.watch(dioProvider)),
);
